# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Gasculator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'IQKeyboardManagerSwift'
  # Pods for Gasculator

end
